# Tomcat
server:
  tomcat:
        max-threads: 1000
        min-spare-threads: 30
  port: 8083
  context-path: /

spring:
  # thymeleaf
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    content-type: text/html


  # mysql
  # 环境 dev|test|pro
  profiles:
    active: dev
  datasource:
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver



mapper:
  mappers: com.gegz.base.BaseMapper
  not-empty: false
  identity: MYSQL
mybatis:
  type-aliases-package: com.gegz.model
  configuration.mapUnderscoreToCamelCase: true